Creditmemo: Invoice: CashOnDeliveryFee.php: Cast string to float
This is required either by PHP8.1 or Magento 2.4.4.

Otherwise it fails:

TypeError: round(): Argument #1 ($num) must be of type int|float, string given in
/vendor/brandung/cash-on-delivery-fee/Model/Total/Invoice/CashOnDeliveryFee.php:21

Fixes: #38

Reported-by: Plastikschnitzer <plastikschnitzer@gmail.com>
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>